using System.Collections.Generic;

namespace BanglaHost.App.Services
{
    public static partial class Localizer
    {
        private static readonly Dictionary<string, string> Map = new Dictionary<string, string>()
        {
{"-- MB", "-- MB"},
{"&gt;_", "&gt;_"},
{"/public_html", "/public_html"},
{"© IT Amadersomaj Inc. All rights reserved.", "© IT Amadersomaj Inc. সর্বস্বত্ব সংরক্ষিত।"},
{"A managed Python interpreter + supervised Python-app sites (Flask / Django / FastAPI / Gunicorn / Uvicorn)", "একটি পরিচালিত Python ইন্টারপ্রেটার + তত্ত্বাবধানে থাকা Python অ্যাপ সাইট (Flask / Django / FastAPI / Gunicorn / Uvicorn)"},
{"About BanglaHost", "BanglaHost সম্পর্কে"},
{"Accept: application/json&#x0a;Authorization: Bearer …", "Accept: application/json&#x0a;Authorization: Bearer …"},
{"Action", "অ্যাকশন"},
{"Actions", "অ্যাকশনসমূহ"},
{"Active jobs", "সক্রিয় কাজসমূহ"},
{"Active Proxy Rules", "সক্রিয় প্রক্সি রুলসমূহ"},
{"Active Queues", "সক্রিয় কিউসমূহ"},
{"Activity log", "অ্যাক্টিভিটি লগ"},
{"Add", "যোগ করুন"},
{"Add Node app", "Node অ্যাপ যোগ করুন"},
{"Add Proxy Rule", "প্রক্সি রুল যোগ করুন"},
{"Add Python app", "Python অ্যাপ যোগ করুন"},
{"Add site", "সাইট যোগ করুন"},
{"admin@example.com", "admin@example.com"},
{"Adminer", "Adminer"},
{"AI Assistant", "AI সহকারী"},
{"All", "সকল"},
{"All guides", "সকল গাইড"},
{"Analysis Results", "বিশ্লেষণের ফলাফল"},
{"Analyze", "বিশ্লেষণ করুন"},
{"Analyze Xdebug cachegrind profiles to find memory leaks and slow functions.", "মেমরি লিক এবং ধীরগতির ফাংশন খুঁজে পেতে Xdebug cachegrind প্রোফাইল বিশ্লেষণ করুন।"},
{"Analyze your project directory to detect the framework, language, database, and missing dependencies.", "ফ্রেমওয়ার্ক, ভাষা, ডেটাবেস এবং অনুপস্থিত ডিপেন্ডেন্সি শনাক্ত করতে আপনার প্রজেক্ট ডিরেক্টরি বিশ্লেষণ করুন।"},
{"Angular", "Angular"},
{"apache", "apache"},
{"Apache (+ nginx, for .htaccess)", "Apache (+ nginx, .htaccess এর জন্য)"},
{"API Tester", "API টেস্টার"},
{"API Token", "API টোকেন"},
{"App behavior", "অ্যাপের আচরণ"},
{"App Threads / Handles", "অ্যাপ থ্রেড / হ্যান্ডেল"},
{"app.local", "app.local"},
{"Ask a question...", "একটি প্রশ্ন জিজ্ঞাসা করুন..."},
{"Ask about your stack. Runs locally through Ollama — no data leaves your machine.", "আপনার স্ট্যাক সম্পর্কে জিজ্ঞাসা করুন। Ollama-এর মাধ্যমে লোকালি চলে — কোনো ডেটা আপনার মেশিন ছেড়ে যায় না।"},
{"Astro", "Astro"},
{"Auth", "অথেনটিকেশন"},
{"Auth values are added to the request headers automatically.", "অথেনটিকেশন ভ্যালুগুলো স্বয়ংক্রিয়ভাবে রিকোয়েস্ট হেডারে যুক্ত হয়।"},
{"Automatically add a .github/workflows directory with a pre-configured CI pipeline.", "একটি প্রি-কনফিগার করা CI পাইপলাইন সহ স্বয়ংক্রিয়ভাবে একটি .github/workflows ডিরেক্টরি যুক্ত করুন।"},
{"Automatically check for updates", "স্বয়ংক্রিয়ভাবে আপডেটের জন্য চেক করুন"},
{"Available Actions", "উপলব্ধ অ্যাকশনসমূহ"},
{"Available shells", "উপলব্ধ শেলসমূহ"},
{"Background Workers", "ব্যাকগ্রাউন্ড ওয়ার্কারসমূহ"},
{"Backup", "ব্যাকআপ"},
{"Backup in progress...", "ব্যাকআপ প্রক্রিয়াধীন..."},
{"Backup Name", "ব্যাকআপের নাম"},
{"BanglaHost is a free and open-source project. If you find it useful and it saves your time, consider buying me a coffee to support its continuous development.", "BanglaHost একটি ফ্রি এবং ওপেন সোর্স প্রজেক্ট। এটি যদি আপনার উপকারে আসে এবং আপনার সময় বাঁচায়, তবে এর ধারাবাহিক উন্নয়নে সহায়তা করতে আমাকে একটি কফি খাওয়াতে পারেন।"},
{"Basic (user + pass)", "বেসিক (ইউজার + পাসওয়ার্ড)"},
{"Bearer token", "Bearer টোকেন"},
{"Better autocomplete for routes, views, config.", "রুট, ভিউ এবং কনফিগের জন্য উন্নত অটো-কমপ্লিট।"},
{"bKash", "বিকাশ"},
{"Blank PHP", "ব্ল্যাঙ্ক PHP"},
{"Block common SQL injection, XSS, and malicious payloads at the web server level.", "ওয়েব সার্ভার স্তরে সাধারণ SQL ইনজেকশন, XSS এবং ক্ষতিকারক পেলোড ব্লক করুন।"},
{"Blueprint Generator", "ব্লুপ্রিন্ট জেনারেটর"},
{"Body", "বডি"},
{"Browse", "ব্রাউজ করুন"},
{"Browse local MySQL databases, tables, and rows directly within BanglaHost.", "সরাসরি BanglaHost-এর মধ্যে লোকাল MySQL ডেটাবেস, টেবিল এবং সারিগুলো ব্রাউজ করুন।"},
{"Browse tables, preview data, and run SQL against local databases.", "টেবিল ব্রাউজ করুন, ডেটা প্রিভিউ করুন এবং লোকাল ডেটাবেসে SQL রান করুন।"},
{"Browse...", "ব্রাউজ করুন..."},
{"Built-in PowerShell 5.1 — always available on Windows", "বিল্ট-ইন PowerShell 5.1 — উইন্ডোজে সর্বদা উপলব্ধ"},
{"C:\\", "C:\\"},
{"C:\\BanglaHost\\sites", "C:\\BanglaHost\\sites"},
{"C:\\BanglaHost\\Sites\\mysite", "C:\\BanglaHost\\Sites\\mysite"},
{"Cache", "ক্যাশ"},
{"Cache Manager", "ক্যাশ ম্যানেজার"},
{"Cached Keys", "ক্যাশ করা কীসমূহ"},
{"CakePHP", "CakePHP"},
{"Cancel", "বাতিল করুন"},
{"Can't find what you're looking for... Join our official Facebook Group to ask questions, share ideas, and get help from other developers.", "আপনি যা খুঁজছেন তা খুঁজে পাচ্ছেন না... প্রশ্ন জিজ্ঞাসা করতে, আইডিয়া শেয়ার করতে এবং অন্যান্য ডেভেলপারদের কাছ থেকে সাহায্য পেতে আমাদের অফিশিয়াল ফেসবুক গ্রুপে যোগ দিন।"},
{"Capture all outgoing emails locally for testing. No real emails sent.", "টেস্টিংয়ের জন্য স্থানীয়ভাবে সমস্ত আউটগোয়িং ইমেইল ক্যাপচার করুন। কোনো বাস্তব ইমেইল পাঠানো হয় না।"},
{"Change PHP…", "PHP পরিবর্তন করুন…"},
{"Change root folder…", "রুট ফোল্ডার পরিবর্তন করুন…"},
{"Change...", "পরিবর্তন করুন..."},
{"Changing the TLD or ports re-renders all vhosts and restarts nginx. After a TLD change, re-issue HTTPS per site.", "TLD বা পোর্ট পরিবর্তন করলে সমস্ত vhost পুনরায় রেন্ডার হয় এবং nginx রিস্টার্ট হয়। TLD পরিবর্তনের পর, প্রতি সাইটের জন্য পুনরায় HTTPS ইস্যু করুন।"},
{"Check", "চেক করুন"},
{"Check for updates", "আপডেটের জন্য চেক করুন"},
{"Checking Docker...", "Docker চেক করা হচ্ছে..."},
{"Checking VS Code installation...", "VS Code ইনস্টলেশন চেক করা হচ্ছে..."},
{"Checking...", "চেক করা হচ্ছে..."},
{"checking…", "চেক করা হচ্ছে…"},
{"Choose &quot;All errors&quot; to see every error/warning from every service in one view.", "এক নজরে প্রতিটি সার্ভিসের সমস্ত এরর/ওয়ার্নিং দেখতে &quot;All errors&quot; নির্বাচন করুন।"},
{"Classic Windows cmd.exe — batch scripts and legacy tools", "ক্লাসিক Windows cmd.exe — ব্যাচ স্ক্রিপ্ট এবং লেগ্যাসি টুলস"},
{"Clear", "ক্লিয়ার করুন"},
{"Clear All Profiles", "সকল প্রোফাইল ক্লিয়ার করুন"},
{"Click Start to open a temporary public https address (via Cloudflare Tunnel). No account, no port-forwarding. Click Stop to end sharing. The public URL is copied to the clipboard when a tunnel comes up.", "একটি অস্থায়ী পাবলিক https ঠিকানা খুলতে Start-এ ক্লিক করুন (Cloudflare Tunnel-এর মাধ্যমে)। কোনো অ্যাকাউন্ট বা পোর্ট-ফরওয়ার্ডিংয়ের প্রয়োজন নেই। শেয়ারিং বন্ধ করতে Stop-এ ক্লিক করুন। টানেল চালু হলে পাবলিক URL ক্লিপবোর্ডে কপি হয়ে যায়।"},
{"Clone", "ক্লোন করুন"},
{"Clone site (Staging)", "সাইট ক্লোন করুন (স্টেজিং)"},
{"Cloudflare Auto-DNS", "Cloudflare Auto-DNS"},
{"Cloudflare Tunnel", "Cloudflare Tunnel"},
{"Code formatter for web technologies.", "ওয়েব প্রযুক্তির জন্য কোড ফরম্যাটার।"},
{"CodeIgniter 4", "CodeIgniter 4"},
{"Command", "কমান্ড"},
{"Command (e.g. php artisan schedule:run)", "কমান্ড (যেমন php artisan schedule:run)"},
{"Command output will appear here...", "কমান্ড আউটপুট এখানে প্রদর্শিত হবে..."},
{"Command Prompt", "Command Prompt"},
{"Common Settings", "সাধারণ সেটিংস"},
{"Company:", "কোম্পানি:"},
{"composer install", "composer install"},
{"Configure php.ini settings per version. Changes automatically restart the PHP worker.", "ভার্সন অনুযায়ী php.ini সেটিংস কনফিগার করুন। পরিবর্তনের ফলে স্বয়ংক্রিয়ভাবে PHP ওয়ার্কার রিস্টার্ট হয়।"},
{"Configure SMTP profiles, test email delivery, and run MailHog for local email capture.", "SMTP প্রোফাইল কনফিগার করুন, ইমেইল ডেলিভারি পরীক্ষা করুন এবং লোকাল ইমেইল ক্যাপচারের জন্য MailHog চালান।"},
{"Connect your GitHub account securely using Device Flow OAuth to manage repository workflows.", "রিপোজিটরি ওয়ার্কফ্লো পরিচালনা করতে Device Flow OAuth ব্যবহার করে নিরাপদে আপনার GitHub অ্যাকাউন্ট সংযুক্ত করুন।"},
{"Connected", "সংযুক্ত"},
{"Contact Support (Email)", "সাপোর্টে যোগাযোগ করুন (ইমেইল)"},
{"Container Logs", "কন্টেইনার লগসমূহ"},
{"Containers", "কন্টেইনারসমূহ"},
{"Copy", "কপি করুন"},
{"Copy Number", "নম্বর কপি করুন"},
{"Copy URL", "URL কপি করুন"},
{"Cost (Time)", "খরচ (সময়)"},
{"CPU", "CPU"},
{"CPU Usage", "CPU ব্যবহার"},
{"Create", "তৈরি করুন"},
{"Create a new backup", "একটি নতুন ব্যাকআপ তৈরি করুন"},
{"Create a new database", "একটি নতুন ডেটাবেস তৈরি করুন"},
{"Create a token at https://github.com/settings/tokens (fine-grained). Grant it: Contents (read/write), Metadata (read), Pull requests (read/write), Issues (read/write). It's stored locally in your BanglaHost config folder; nothing is sent to Anthropic.", "https://github.com/settings/tokens-এ একটি টোকেন তৈরি করুন (fine-grained)। এতে অনুমতি দিন: Contents (read/write), Metadata (read), Pull requests (read/write), Issues (read/write)। এটি আপনার BanglaHost কনফিগ ফোল্ডারে স্থানীয়ভাবে সংরক্ষণ করা হয়; Anthropic-এ কিছুই পাঠানো হয় না।"},
{"Create new project from blueprint", "ব্লুপ্রিন্ট থেকে নতুন প্রজেক্ট তৈরি করুন"},
{"Create, manage, and debug containerized apps.", "কন্টেইনারাইজড অ্যাপ তৈরি, পরিচালনা এবং ডিবাগ করুন।"},
{"Cron &amp; Queue Manager", "Cron &amp; Queue ম্যানেজার"},
{"Cron (e.g. 0 * * * *)", "Cron (যেমন 0 * * * *)"},
{"Cron-style scheduled tasks. Backed by Windows Task Scheduler under the hood.", "Cron-স্টাইলের শিডিউল করা টাস্ক। নেপথ্যে Windows Task Scheduler দ্বারা পরিচালিত।"},
{"Cross-platform PowerShell 7+", "ক্রস-প্ল্যাটফর্ম PowerShell 7+"},
{"Dashboard", "ড্যাশবোর্ড"},
{"Dashboard list â€” sites per page", "ড্যাশবোর্ড তালিকা — প্রতি পৃষ্ঠায় সাইট"},
{"Data directory", "ডাটা ডিরেক্টরি"},
{"Database", "ডাটাবেজ"},
{"Database Explorer", "ডাটাবেজ এক্সপ্লোরার"},
{"Database Management", "ডাটাবেজ ম্যানেজমেন্ট"},
{"Database:", "ডাটাবেজ:"},
{"Databases", "ডাটাবেজসমূহ"},
{"DB tools:", "DB টুলস:"},
{"default", "ডিফল্ট"},
{"Default PHP", "ডিফল্ট PHP"},
{"Default web server", "ডিফল্ট ওয়েব সার্ভার"},
{"Del", "মুছুন"},
{"DELETE", "DELETE"},
{"Delete", "মুছুন"},
{"Delete All", "সব মুছুন"},
{"Deploy your local sites to production servers with a single click.", "এক ক্লিকেই আপনার লোকাল সাইটগুলো প্রোডাকশন সার্ভারে ডিপ্লয় করুন।"},
{"Deployment", "ডিপ্লয়মেন্ট"},
{"Deployment Method", "ডিপ্লয়মেন্ট পদ্ধতি"},
{"Deployment Profiles", "ডিপ্লয়মেন্ট প্রোফাইলসমূহ"},
{"Developer Information", "ডেভেলপার তথ্য"},
{"Developer:", "ডেভেলপার:"},
{"Development Preset", "ডেভেলপমেন্ট প্রিসেট"},
{"Dismiss", "খারিজ করুন"},
{"display_errors", "display_errors"},
{"DNS Checker", "DNS চেকার"},
{"Docker", "Docker"},
{"Docker Manager", "Docker ম্যানেজার"},
{"Documentation", "ডকুমেন্টেশন"},
{"Documentation &amp; Guides", "ডকুমেন্টেশন &amp; গাইড"},
{"Domain (e.g., app.local)", "ডোমেইন (যেমন, app.local)"},
{"Domain Name", "ডোমেইন নাম"},
{"domain.test", "domain.test"},
{"Domains &amp; DNS", "ডোমেইন &amp; DNS"},
{"Domains, ports &amp; defaults", "ডোমেইন, পোর্ট &amp; ডিফল্টসমূহ"},
{"Download, install, and switch PHP versions directly from windows.php.net.", "windows.php.net থেকে সরাসরি PHP সংস্করণ ডাউনলোড, ইনস্টল এবং পরিবর্তন করুন।"},
{"Drop", "ড্রপ করুন"},
{"Drupal", "Drupal"},
{"e.g. C:\\Projects\\MyAwesomeApp", "যেমন C:\\Projects\\MyAwesomeApp"},
{"e.g. mysite.test or example.com", "যেমন mysite.test অথবা example.com"},
{"Each button opens a brand-new console window at the working directory above — the same experience as XAMPP's 'Shell'. Close the window when you are done; the app stays running.", "প্রতিটি বাটন উপরের ওয়ার্কিং ডিরেক্টরিতে একটি নতুন কনসোল উইন্ডো খোলে — যা XAMPP-এর 'Shell'-এর মতোই। কাজ শেষে উইন্ডোটি বন্ধ করুন; অ্যাপটি চালু থাকবে।"},
{"Edit .env (backend)", ".env এডিট করুন (ব্যাকএন্ড)"},
{"Edit .env (frontend)", ".env এডিট করুন (ফ্রন্টএন্ড)"},
{"Edit config", "কনফিগ এডিট করুন"},
{"Edit php.ini", "php.ini এডিট করুন"},
{"Edit Profile", "প্রোফাইল এডিট করুন"},
{"Email &amp; SMTP", "ইমেইল &amp; SMTP"},
{"Email (for Let's Encrypt expiry notices)", "ইমেইল (Let's Encrypt মেয়াদের নোটিসের জন্য)"},
{"Email Send Log", "ইমেইল প্রেরণের লগ"},
{"Engine", "ইঞ্জিন"},
{"English", "ইংরেজি"},
{"Enter this code on GitHub:", "GitHub-এ এই কোডটি প্রবেশ করান:"},
{"Environment File (.env)", "এনভায়রনমেন্ট ফাইল (.env)"},
{"Environment Variables", "এনভায়রনমেন্ট ভ্যারিয়েবলসমূহ"},
{"Errors only", "শুধুমাত্র ত্রুটিসমূহ"},
{"Essential code intelligence for PHP.", "PHP-এর জন্য প্রয়োজনীয় কোড ইন্টেলিজেন্স।"},
{"example.com", "example.com"},
{"Execute", "এক্সিকিউট করুন"},
{"Export", "এক্সপোর্ট করুন"},
{"Extensions", "এক্সটেনশনসমূহ"},
{"Extra Arguments", "অতিরিক্ত আর্গুমেন্টসমূহ"},
{"Facebook Group:", "Facebook গ্রুপ:"},
{"Facebook Profile:", "Facebook প্রোফাইল:"},
{"Failed to launch shell", "শেল চালু করতে ব্যর্থ হয়েছে"},
{"File", "ফাইল"},
{"File Manager", "ফাইল ম্যানেজার"},
{"filter tables…", "টেবিল ফিল্টার করুন…"},
{"filter...", "ফিল্টার করুন..."},
{"Flush", "ফ্লাশ করুন"},
{"Flush All", "সব ফ্লাশ করুন"},
{"Folder", "ফোল্ডার"},
{"Form URL-encoded", "Form URL-encoded"},
{"Format JSON", "JSON ফরম্যাট করুন"},
{"Found a glitch or an issue... Post it in our community group so we can fix it in the next update.", "কোনো ত্রুটি বা সমস্যা খুঁজে পেয়েছেন... আমাদের কমিউনিটি গ্রুপে পোস্ট করুন যাতে আমরা পরবর্তী আপডেটে তা সমাধান করতে পারি।"},
{"Framework:", "ফ্রেমওয়ার্ক:"},
{"FTP", "FTP"},
{"Function Name", "ফাংশনের নাম"},
{"Generate", "জেনারেট করুন"},
{"Generate Let's Encrypt", "Let's Encrypt জেনারেট করুন"},
{"Generate Local (mkcert)", "লোকাল (mkcert) জেনারেট করুন"},
{"Generate New Certificate", "নতুন সার্টিফিকেট জেনারেট করুন"},
{"Generate Workflow", "ওয়ার্কফ্লো জেনারেট করুন"},
{"Generating Certificate...", "সার্টিফিকেট জেনারেট করা হচ্ছে..."},
{"GET", "GET"},
{"Getting Started", "শুরু করার নির্দেশিকা"},
{"ghp_...", "ghp_..."},
{"git", "git"},
{"Git", "Git"},
{"Git Bash", "Git Bash"},
{"Git for Windows bash — POSIX-style shell", "Git for Windows bash — POSIX-স্টাইল শেল"},
{"git@github.com:user/repo.git  or  https://github.com/user/repo.git", "git@github.com:user/repo.git  অথবা  https://github.com/user/repo.git"},
{"GitHub", "GitHub"},
{"GitHub Account", "GitHub অ্যাকাউন্ট"},
{"GitHub Actions", "GitHub Actions"},
{"Go", "যান"},
{"Go to", "এখানে যান"},
{"Go to Sites Root", "সাইটের রুট ডিরেক্টরিতে যান"},
{"Have an idea to make BanglaHost even better... Share your feature request with the community.", "BanglaHost-কে আরও উন্নত করার কোনো আইডিয়া আছে... কমিউনিটির সাথে আপনার ফিচার অনুরোধ শেয়ার করুন।"},
{"HEAD", "HEAD"},
{"Headers", "হেডারসমূহ"},
{"Health Report", "হেলথ রিপোর্ট"},
{"Hello! I'm your BanglaHost AI Assistant. I can help you manage your local web server and sites. How can I help you today...", "হ্যালো! আমি আপনার BanglaHost এআই অ্যাসিস্ট্যান্ট। আমি আপনাকে লোকাল ওয়েব সার্ভার এবং সাইটগুলো পরিচালনা করতে সাহায্য করতে পারি। আজ আপনাকে কীভাবে সাহায্য করতে পারি..."},
{"Help &amp; Support", "সহায়তা &amp; সাপোর্ট"},
{"Hit Ratio", "হিট রেশিও"},
{"Host / Server IP", "হোস্ট / সার্ভার IP"},
{"How to connect to MySQL/PostgreSQL and use the SQL Studio.", "কীভাবে MySQL/PostgreSQL-এ সংযোগ করবেন এবং SQL Studio ব্যবহার করবেন।"},
{"HTML", "HTML"},
{"HTTP port", "HTTP পোর্ট"},
{"HTTPS", "HTTPS"},
{"HTTPS port", "HTTPS পোর্ট"},
{"https://api.example.com/users  —  or  http://myapp.test/api/ping", "https://api.example.com/users  —  অথবা  http://myapp.test/api/ping"},
{"Image name (e.g. mysql:8)", "ইমেজের নাম (যেমন mysql:8)"},
{"Images", "ইমেজসমূহ"},
{"Import", "ইমপোর্ট করুন"},
{"Inbox is empty", "ইনবক্স খালি"},
{"Install", "ইনস্টল করুন"},
{"Install downloads portable builds on demand into BanglaHost's own bin folder.", "ইনস্টল করলে চাহিদা অনুযায়ী পোর্টেবল বিল্ডগুলো সরাসরি BanglaHost-এর নিজস্ব bin ফোল্ডারে ডাউনলোড হবে।"},
{"Install Ollama", "Ollama ইনস্টল করুন"},
{"Install PHP", "PHP ইনস্টল করুন"},
{"Install PostgreSQL", "PostgreSQL ইনস্টল করুন"},
{"Install Python", "Python ইনস্টল করুন"},
{"Install SSL (HTTPS)", "SSL (HTTPS) ইনস্টল করুন"},
{"Installation, directory structure, and basic project setup guide.", "ইনস্টলেশন, ডিরেক্টরি কাঠামো এবং বেসিক প্রজেক্ট সেটআপ নির্দেশিকা।"},
{"Installed Certificates", "ইনস্টল করা সার্টিফিকেটসমূহ"},
{"Installed PHP Versions", "ইনস্টল করা PHP ভার্সনসমূহ"},
{"Interpreter", "ইন্টারপ্রেটার"},
{"IP Address", "IP অ্যাড্রেস"},
{"IT Amadersomaj Inc.", "IT Amadersomaj Inc."},
{"Job name", "জবের নাম"},
{"Join Facebook Group", "ফেসবুক গ্রুপে যোগ দিন"},
{"Join the Community", "কমিউনিটিতে যোগ দিন"},
{"Joomla", "Joomla"},
{"JSON", "JSON"},
{"Keep running in the system tray when the window is closed", "উইন্ডো বন্ধ থাকলেও সিস্টেম ট্রে-তে চালু রাখুন"},
{"Key pattern (e.g. laravel_cache:*)", "কী প্যাটার্ন (যেমন laravel_cache:*)"},
{"Laminas", "Laminas"},
{"Language:", "ভাষা:"},
{"Laravel", "Laravel"},
{"Laravel API + Vite", "Laravel API + Vite"},
{"Laravel Extra Intellisense", "Laravel Extra Intellisense"},
{"latest", "সর্বশেষ"},
{"Launch your sites in Visual Studio Code and manage recommended extensions.", "Visual Studio Code-এ আপনার সাইটগুলো চালু করুন এবং প্রস্তাবিত এক্সটেনশনসমূহ পরিচালনা করুন।"},
{"Learn how to make the most out of BanglaHost. Click any topic to read the guide.", "BanglaHost-এর সর্বোচ্চ সুবিধা কীভাবে পাবেন তা জানুন। গাইডটি পড়তে যেকোনো বিষয়ে ক্লিক করুন।"},
{"Legal &amp; Resources", "আইনি ও রিসোর্স"},
{"License Information", "লাইসেন্স তথ্য"},
{"Listening Ports", "লিসেনিং পোর্টসমূহ"},
{"Live Cloudflare Tunnels", "লাইভ Cloudflare টানেলসমূহ"},
{"Live Log Viewer", "লাইভ লগ ভিউয়ার"},
{"Local domains (*.test) use mkcert. Public domains can use Let's Encrypt.", "লোকাল ডোমেইনে (*.test) mkcert ব্যবহার হয়। পাবলিক ডোমেইনে Let's Encrypt ব্যবহার করা যেতে পারে।"},
{"Local Email Inbox", "লোকাল ইমেইল ইনবক্স"},
{"Local HOSTS Entries", "লোকাল HOSTS এন্ট্রি"},
{"Local repositories", "লোকাল রিপোজিটরি"},
{"Local Source Directory", "লোকাল সোর্স ডিরেক্টরি"},
{"Local SSL (HTTPS)", "লোকাল SSL (HTTPS)"},
{"Local web stack", "লোকাল ওয়েব স্ট্যাক"},
{"Location:", "লোকেশন:"},
{"Log", "লগ"},
{"Login with GitHub", "GitHub দিয়ে লগইন করুন"},
{"Logs", "লগসমূহ"},
{"lts", "lts"},
{"MailHog (Local Email Trap)", "MailHog (লোকাল ইমেইল ট্র্যাপ)"},
{"Mailpit", "Mailpit"},
{"Make Default", "ডিফল্ট করুন"},
{"Malware &amp; Vulnerability Scanner", "ম্যালওয়্যার ও ভালনারেবিলিটি স্ক্যানার"},
{"Manage .env files for your sites easily.", "সহজেই আপনার সাইটগুলোর .env ফাইল পরিচালনা করুন।"},
{"Manage background schedule:work and queue:work for your local Laravel projects.", "আপনার লোকাল Laravel প্রজেক্টের ব্যাকগ্রাউন্ড schedule:work এবং queue:work পরিচালনা করুন।"},
{"Manage Docker containers, images, and compose stacks from BanglaHost.", "BanglaHost থেকেই Docker কন্টেইনার, ইমেজ এবং কম্পোজ স্ট্যাক পরিচালনা করুন।"},
{"Manage local HOSTS file routing, check DNS propagation, and update Cloudflare DNS.", "লোকাল HOSTS ফাইল রাউটিং পরিচালনা করুন, DNS প্রপাগেশন পরীক্ষা করুন এবং Cloudflare DNS আপডেট করুন।"},
{"Manage local mkcert certificates and production Let's Encrypt certificates.", "লোকাল mkcert সার্টিফিকেট এবং প্রোডাকশনের Let's Encrypt সার্টিফিকেট পরিচালনা করুন।"},
{"Manage local repositories under your Sites folder and connect to GitHub.", "Sites ফোল্ডারের অধীনে লোকাল রিপোজিটরি পরিচালনা করুন এবং GitHub-এর সাথে যুক্ত করুন।"},
{"Manage PHP extensions, install PECL modules, and configure ionCube loader.", "PHP এক্সটেনশন পরিচালনা করুন, PECL মডিউল ইনস্টল করুন এবং ionCube লোডার কনফিগার করুন।"},
{"Map a local domain to a port running on localhost.", "localhost-এ চলমান একটি পোর্টের সাথে লোকাল ডোমেন ম্যাপ করুন।"},
{"Marketplace", "মার্কেটপ্লেস"},
{"max_execution_time", "max_execution_time"},
{"Memory", "মেমরি"},
{"Memory (Available)", "মেমরি (উপলব্ধ)"},
{"Memory Used", "ব্যবহৃত মেমরি"},
{"memory_limit", "memory_limit"},
{"ModSecurity / WAF Engine", "ModSecurity / WAF ইঞ্জিন"},
{"Mohammad Sheikh Shahinur Rahman", "Mohammad Sheikh Shahinur Rahman"},
{"Monitor and manage Redis queues, Laravel Horizon jobs, and background workers.", "Redis কিউ, Laravel Horizon জব এবং ব্যাকগ্রাউন্ড ওয়ার্কার পর্যবেক্ষণ ও পরিচালনা করুন।"},
{"Monitor listening ports, network interfaces, and system performance.", "লিসেনিং পোর্ট, নেটওয়ার্ক ইন্টারফেস এবং সিস্টেম পারফরম্যান্স পর্যবেক্ষণ করুন।"},
{"Monitor Redis cache and PHP OPCache. Flush, inspect keys, and optimize.", "Redis ক্যাশ এবং PHP OPCache পর্যবেক্ষণ করুন। ফ্লাশ করুন, কীগুলো পরীক্ষা করুন এবং অপ্টিমাইজ করুন।"},
{"Multiple Node versions via fnm + supervised Node-app sites", "fnm-এর মাধ্যমে একাধিক Node ভার্সন + নিয়ন্ত্রিত Node-app সাইটসমূহ"},
{"Multiple PHP Versions", "একাধিক PHP ভার্সন"},
{"MySQL / MariaDB", "MySQL / MariaDB"},
{"Network", "নেটওয়ার্ক"},
{"Network Inspector", "নেটওয়ার্ক ইন্সপেক্টর"},
{"Network Interfaces", "নেটওয়ার্ক ইন্টারফেসসমূহ"},
{"new database name", "নতুন ডাটাবেসের নাম"},
{"Next.js", "Next.js"},
{"nginx", "nginx"},
{"nginx (serves PHP)", "nginx (PHP সার্ভ করে)"},
{"No custom blueprints yet. Add a site with the settings you like, then use the site's menu (Save as blueprint) to keep it as a reusable template.", "এখনও কোনো কাস্টম ব্লুপ্রিন্ট নেই। আপনার পছন্দসই সেটিংস সহ একটি সাইট যোগ করুন, তারপর এটিকে পুনরায় ব্যবহারযোগ্য টেমপ্লেট হিসেবে রাখতে সাইটের মেনু (Save as blueprint) ব্যবহার করুন।"},
{"No databases yet.", "এখনও কোনো ডাটাবেস নেই।"},
{"no engine running", "কোনো ইঞ্জিন চলছে না"},
{"No git repositories found under your Sites folder yet.", "আপনার Sites ফোল্ডারের অধীনে এখনও কোনো git রিপোজিটরি পাওয়া যায়নি।"},
{"No jobs scheduled yet.", "এখনও কোনো জব শিডিউল করা হয়নি।"},
{"No Node apps yet.", "এখনও কোনো Node অ্যাপ নেই।"},
{"No Node versions installed yet.", "এখনও কোনো Node ভার্সন ইনস্টল করা হয়নি।"},
{"No Python apps yet. Click &#x201C;Add Python app&#x201D;.", "এখনও কোনো Python অ্যাপ নেই। &#x201C;Add Python app&#x201D;-এ ক্লিক করুন।"},
{"No scan performed or no issues found.", "কোনো স্ক্যান চালানো হয়নি অথবা কোনো সমস্যা পাওয়া যায়নি।"},
{"No sites yet.", "এখনও কোনো সাইট নেই।"},
{"No sites yet. Add one on the Sites page.", "এখনও কোনো সাইট নেই। সাইট পেজে একটি যোগ করুন।"},
{"Node", "Node"},
{"Node app", "Node অ্যাপ"},
{"Node apps", "Node অ্যাপসমূহ"},
{"Node Version:", "Node ভার্সন:"},
{"Node.js", "Node.js"},
{"None", "কোনোটিই নয়"},
{"Not signed in.", "সাইন ইন করা নেই।"},
{"npm install", "npm install"},
{"npm install (backend)", "npm install (backend)"},
{"npm install (frontend)", "npm install (frontend)"},
{"NPM Scripts Runner", "NPM স্ক্রিপ্টস রানার"},
{"Nuxt 3", "Nuxt 3"},
{"Off", "বন্ধ"},
{"Off â€” closing the window quits BanglaHost", "বন্ধ — উইন্ডো বন্ধ করলে BanglaHost বন্ধ হয়ে যাবে"},
{"Ollama is not running", "Ollama চলছে না"},
{"On", "চালু"},
{"On â€” sites stay up in the background", "চালু — সাইটগুলো ব্যাকগ্রাউন্ডে চালু থাকবে"},
{"One per line — Key: Value", "প্রতি লাইনে একটি — Key: Value"},
{"One-click installers for popular apps, tools and frameworks.", "জনপ্রিয় অ্যাপ, টুলস এবং ফ্রেমওয়ার্কের জন্য ওয়ান-ক্লিক ইনস্টলার।"},
{"Open", "খুলুন"},
{"Open a native shell in your project directory. PowerShell, CMD, Git Bash, or WSL — one click launches a real console window.", "আপনার প্রজেক্ট ডিরেক্টরিতে একটি নেটিভ শেল খুলুন। PowerShell, CMD, Git Bash, বা WSL — এক ক্লিকেই রিয়েল কনসোল উইন্ডো চালু হয়।"},
{"Open data folder", "ডাটা ফোল্ডার খুলুন"},
{"Open folder", "ফোল্ডার খুলুন"},
{"Open GitHub to Authorize", "অথরাইজ করতে GitHub খুলুন"},
{"Open in code editor", "কোড এডিটরে খুলুন"},
{"Open in phpMyAdmin", "phpMyAdmin-এ খুলুন"},
{"Open in VS Code", "VS Code-এ খুলুন"},
{"Open Site in VS Code", "সাইটটি VS Code-এ খুলুন"},
{"Open terminal here", "এখানে টার্মিনাল খুলুন"},
{"Open UI (8025)", "UI খুলুন (8025)"},
{"OPTIONS", "OPTIONS"},
{"Output Log", "আউটপুট লগ"},
{"Package Manager", "প্যাকেজ ম্যানেজার"},
{"Package Manager:", "প্যাকেজ ম্যানেজার:"},
{"password", "পাসওয়ার্ড"},
{"Password / App Key", "পাসওয়ার্ড / অ্যাপ কি"},
{"Password / Auth Token", "পাসওয়ার্ড / অথ টোকেন"},
{"Password…", "পাসওয়ার্ড…"},
{"PATCH", "PATCH"},
{"Performance Profiler", "পারফরম্যান্স প্রোফাইলার"},
{"Personal access token", "পার্সোনাল অ্যাক্সেস টোকেন"},
{"Personal Account", "ব্যক্তিগত অ্যাকাউন্ট"},
{"PHP", "PHP"},
{"PHP (plain)", "PHP (সাধারণ)"},
{"PHP Extensions", "PHP এক্সটেনশন"},
{"PHP INI Manager", "PHP INI ম্যানেজার"},
{"PHP Intelephense", "PHP Intelephense"},
{"PHP OPCache", "PHP OPCache"},
{"PHP Version Manager", "PHP ভার্সন ম্যানেজার"},
{"PHP Version:", "PHP ভার্সন:"},
{"phpMyAdmin", "phpMyAdmin"},
{"pip install", "pip install"},
{"Port", "পোর্ট"},
{"POST", "POST"},
{"post_max_size", "post_max_size"},
{"PostgreSQL", "PostgreSQL"},
{"PowerShell 7", "PowerShell 7"},
{"Prettier", "Prettier"},
{"Privacy Policy", "গোপনীয়তা নীতি"},
{"Production Preset", "প্রোডাকশন প্রিসেট"},
{"Profile Name", "প্রোফাইলের নাম"},
{"Project Directory", "প্রজেক্ট ডিরেক্টরি"},
{"Project Health &amp; Missing Dependencies", "প্রজেক্টের স্বাস্থ্য &amp; মিসিং ডিপেন্ডেন্সি"},
{"Project Type", "প্রজেক্টের ধরন"},
{"Publish a local site to the internet in one click.", "এক ক্লিকেই লোকাল সাইট ইন্টারনেটে প্রকাশ করুন।"},
{"Pull", "পুল করুন"},
{"Pull &amp; Run", "পুল &amp; রান করুন"},
{"Push", "পুশ করুন"},
{"PUT", "PUT"},
{"Python", "Python"},
{"Python app", "Python অ্যাপ"},
{"Python apps", "Python অ্যাপসমূহ"},
{"Queue List", "কিউ তালিকা"},
{"Queue Manager", "কিউ ম্যানেজার"},
{"Queue Worker", "কিউ ওয়ার্কার"},
{"Quick App", "কুইক অ্যাপ"},
{"Quick Install:", "দ্রুত ইনস্টল:"},
{"Quick install:", "দ্রুত ইনস্টল:"},
{"Quick Run", "কুইক রান"},
{"Raw text", "র টেক্সট"},
{"React", "React"},
{"React (Vite)", "React (Vite)"},
{"Ready", "প্রস্তুত"},
{"Recent Backups", "সাম্প্রতিক ব্যাকআপসমূহ"},
{"recipient@example.com", "recipient@example.com"},
{"Recommended Extensions", "প্রস্তাবিত এক্সটেনশনসমূহ"},
{"Redis Keys", "Redis কি-সমূহ"},
{"Redis Server Info", "Redis সার্ভার তথ্য"},
{"Redis Status", "Redis স্ট্যাটাস"},
{"Refresh", "রিফ্রেশ করুন"},
{"Refresh Profiles", "প্রোফাইল রিফ্রেশ করুন"},
{"Refresh Status", "স্ট্যাটাস রিফ্রেশ করুন"},
{"Reinstall (update)", "পুনরায় ইনস্টল করুন (আপডেট)"},
{"Reinstall SSL (fresh certificate)", "SSL পুনরায় ইনস্টল করুন (নতুন সার্টিফিকেট)"},
{"Release Date:", "প্রকাশের তারিখ:"},
{"Remote Path", "রিমোট পাথ"},
{"Remove", "সরিয়ে ফেলুন"},
{"Remove SSL", "SSL সরিয়ে ফেলুন"},
{"Report a Bug", "বাগ রিপোর্ট করুন"},
{"Request", "রিকোয়েস্ট"},
{"Request a Feature", "নতুন ফিচারের অনুরোধ করুন"},
{"Requires DNS Edit permissions", "DNS এডিট করার অনুমতির প্রয়োজন"},
{"Requires UAC elevation to update.", "আপডেট করতে UAC এলিভেশন প্রয়োজন।"},
{"Reset", "রিসেট করুন"},
{"Reset OPCache", "OPCache রিসেট করুন"},
{"Response", "রেসপন্স"},
{"Restart", "রিস্টার্ট করুন"},
{"Restore", "রিস্টোর করুন"},
{"Reverse Proxy", "রিভার্স প্রক্সি"},
{"Revert", "পূর্বাবস্থায় ফেরান"},
{"Revoke / Delete", "বাতিল / মুছে ফেলুন"},
{"Rm", "Rm"},
{"Root Directory", "রুট ডিরেক্টরি"},
{"Root password…", "রুট পাসওয়ার্ড…"},
{"Route domains to local development ports (Node.js, Go, Python, etc.).", "ডোমেনগুলোকে লোকাল ডেভেলপমেন্ট পোর্টে রাউট করুন (Node.js, Go, Python, ইত্যাদি)।"},
{"Run", "রান করুন"},
{"Run Composer and NPM commands for your sites.", "আপনার সাইটের জন্য Composer এবং NPM কমান্ড চালান।"},
{"Run Diagnostics", "ডায়াগনস্টিকস চালান"},
{"Run diagnostics to check for common issues, missing dependencies, or misconfigurations.", "সাধারণ সমস্যা, অনুপস্থিত ডিপেন্ডেন্সি বা ভুল কনফিগারেশন পরীক্ষা করতে ডায়াগনস্টিকস চালান।"},
{"Save", "সেভ করুন"},
{"Save &amp; Restart", "সেভ করুন &amp; রিস্টার্ট দিন"},
{"Save Profile", "প্রোফাইল সেভ করুন"},
{"Save reusable site templates and spin up a new project in one click.", "পুনর্ব্যবহারযোগ্য সাইট টেমপ্লেট সেভ করুন এবং এক ক্লিকেই নতুন প্রজেক্ট তৈরি করুন।"},
{"Save token", "টোকেন সেভ করুন"},
{"Saved blueprints", "সংরক্ষিত ব্লুপ্রিন্ট"},
{"Scaffold CI/CD workflows for your local projects to run tests and deployments on GitHub.", "GitHub-এ টেস্ট ও ডিপ্লয়মেন্ট চালানোর জন্য আপনার লোকাল প্রজেক্টের CI/CD ওয়ার্কফ্লো তৈরি করুন।"},
{"Scaffold Workflow", "ওয়ার্কফ্লো তৈরি করুন"},
{"Scan for vulnerabilities and manage the Web Application Firewall.", "নিরাপত্তা ঝুঁকির জন্য স্ক্যান করুন এবং Web Application Firewall পরিচালনা করুন।"},
{"Scan Results", "স্ক্যান ফলাফল"},
{"Scans your project files for known backdoors, web shells, and dangerous patterns.", "পরিচিত ব্যাকডোর, ওয়েব শেল এবং বিপজ্জনক প্যাটার্নের জন্য আপনার প্রজেক্ট ফাইলগুলো স্ক্যান করে।"},
{"Schedule", "শিডিউল"},
{"Schedule a new job", "নতুন জব শিডিউল করুন"},
{"Schedule Worker", "শিডিউল ওয়ার্কার"},
{"Script Name", "স্ক্রিপ্টের নাম"},
{"Search", "অনুসন্ধান"},
{"Search extensions...", "এক্সটেনশন খুঁজুন..."},
{"search…", "খুঁজুন…"},
{"Securing your *.test domains with mkcert and fixing browser warnings.", "mkcert দিয়ে আপনার *.test ডোমেন সুরক্ষিত করা এবং ব্রাউজারের সতর্কতা ঠিক করা।"},
{"Security &amp; WAF", "সিকিউরিটি &amp; WAF"},
{"SELECT * FROM table LIMIT 100", "SELECT * FROM table LIMIT 100"},
{"SELECT * FROM users LIMIT 100;", "SELECT * FROM users LIMIT 100;"},
{"select a database", "একটি ডাটাবেস নির্বাচন করুন"},
{"Select a database on the left, then pick a table or run a query.", "বাম পাশ থেকে একটি ডাটাবেস নির্বাচন করুন, তারপর একটি টেবিল বাছুন অথবা কুয়েরি চালান।"},
{"Select a file to view or edit", "দেখতে বা সম্পাদনা করতে একটি ফাইল নির্বাচন করুন"},
{"Select a log file to watch...", "দেখার জন্য একটি লগ ফাইল নির্বাচন করুন..."},
{"Select a Node.js project to view and run its package.json scripts visually.", "ভিজ্যুয়ালি package.json স্ক্রিপ্ট দেখতে ও চালাতে একটি Node.js প্রজেক্ট নির্বাচন করুন।"},
{"Select a profile file", "একটি প্রোফাইল ফাইল নির্বাচন করুন"},
{"Select a Project", "একটি প্রজেক্ট নির্বাচন করুন"},
{"Select a site to run health checks.", "হেলথ চেক চালানোর জন্য একটি সাইট নির্বাচন করুন।"},
{"Select an email to view", "দেখার জন্য একটি ইমেইল নির্বাচন করুন"},
{"Select PHP Version:", "PHP ভার্সন নির্বাচন করুন:"},
{"Select Project Directory", "প্রজেক্ট ডিরেক্টরি নির্বাচন করুন"},
{"Select Site", "সাইট নির্বাচন করুন"},
{"Send", "পাঠান"},
{"Send a request to see the response here.", "রেসপন্স দেখতে এখানে একটি রিকোয়েস্ট পাঠান।"},
{"Send an email directly to the developer for private inquiries or business support.", "ব্যক্তিগত অনুসন্ধান বা ব্যবসায়িক সহায়তার জন্য সরাসরি ডেভেলপারের কাছে ইমেল পাঠান।"},
{"Send HTTP requests to any endpoint — local or public. Postman-lite, built in.", "যেকোনো এন্ডপয়েন্টে HTTP রিকোয়েস্ট পাঠান — লোকাল বা পাবলিক। বিল্ট-ইন Postman-lite।"},
{"Send Money", "টাকা পাঠান"},
{"Send Test Email", "টেস্ট ইমেল পাঠান"},
{"Services", "সার্ভিসসমূহ"},
{"Setting up Laravel Queues, Cron jobs, and running NPM scripts.", "Laravel Queues, Cron jobs সেটআপ এবং NPM scripts চালানো।"},
{"Settings", "সেটিংস"},
{"SFTP", "SFTP"},
{"shahinalam3546@gmail.com", "shahinalam3546@gmail.com"},
{"Sharing your local site publicly using Cloudflare tunnels.", "Cloudflare tunnels ব্যবহার করে আপনার লোকাল সাইট সার্বজনীনভাবে শেয়ার করা।"},
{"Show", "দেখান"},
{"Show tables", "টেবিল দেখান"},
{"Sign out", "সাইন আউট"},
{"Sign Out", "সাইন আউট"},
{"Site Health Check", "সাইট হেলথ চেক"},
{"Site Name", "সাইটের নাম"},
{"site name (e.g. myapp)", "সাইটের নাম (যেমন myapp)"},
{"site name (e.g. myshop)", "সাইটের নাম (যেমন myshop)"},
{"Sites", "সাইটসমূহ"},
{"Sites page â€” sites per page", "সাইট পেজ — প্রতি পেজে সাইটের সংখ্যা"},
{"Sites root", "সাইটের রুট"},
{"Slim", "Slim"},
{"Slim REST API", "Slim REST API"},
{"Smart Project Detection", "স্মার্ট প্রজেক্ট শনাক্তকরণ"},
{"SMTP Host", "SMTP হোস্ট"},
{"SMTP Profile", "SMTP প্রোফাইল"},
{"smtp.gmail.com", "smtp.gmail.com"},
{"Snapshot every site and database into a single compressed archive.", "প্রতিটি সাইট এবং ডাটাবেসের স্ন্যাপশট একটি একক কম্প্রেসড আর্কাইভে সংরক্ষণ করুন।"},
{"SQL", "SQL"},
{"SQL Studio", "SQL Studio"},
{"SSH", "SSH"},
{"SSL Certificates", "SSL সার্টিফিকেটসমূহ"},
{"Start", "চালু করুন"},
{"Start all", "সব চালু করুন"},
{"Start BanglaHost at login", "লগইনের সময় BanglaHost চালু করুন"},
{"Start Full Backup", "সম্পূর্ণ ব্যাকআপ শুরু করুন"},
{"Start MailHog", "MailHog চালু করুন"},
{"Start Security Scan", "সিকিউরিটি স্ক্যান শুরু করুন"},
{"Start services when BanglaHost launches", "BanglaHost চালু হলে সার্ভিসসমূহ চালু করুন"},
{"Static HTML", "Static HTML"},
{"Status", "স্ট্যাটাস"},
{"Stop", "বন্ধ করুন"},
{"Stop all", "সব বন্ধ করুন"},
{"Stop Process", "প্রসেস বন্ধ করুন"},
{"Storage", "স্টোরেজ"},
{"Support BanglaHost", "BanglaHost-কে সাপোর্ট করুন"},
{"Support Email:", "সাপোর্ট ইমেল:"},
{"SvelteKit", "SvelteKit"},
{"Switch to apache", "apache-এ পরিবর্তন করুন"},
{"Switch to nginx", "nginx-এ পরিবর্তন করুন"},
{"Switching PHP versions, managing extensions, and editing php.ini.", "PHP ভার্সন পরিবর্তন, এক্সটেনশন পরিচালনা এবং php.ini এডিট করা।"},
{"Symfony", "Symfony"},
{"Symfony (skeleton)", "Symfony (skeleton)"},
{"Tables", "টেবিলসমূহ"},
{"Target Directory", "টার্গেট ডিরেক্টরি"},
{"Target IP", "টার্গেট আইপি"},
{"Target Port (e.g., 3000)", "টার্গেট পোর্ট (যেমন, 3000)"},
{"Task Scheduler", "টাস্ক শিডিউলার"},
{"Terminal", "টার্মিনাল"},
{"Test Recipient", "টেস্ট প্রাপক"},
{"Thank you for your love and support! ......", "আপনার ভালোবাসা ও সমর্থনের জন্য ধন্যবাদ! ......"},
{"The selected shell starts with this folder as its current directory.", "নির্বাচিত শেল এই ফোল্ডারটিকে তার বর্তমান ডিরেক্টরি হিসেবে রেখে শুরু হবে।"},
{"Third-party Licenses", "থার্ড-পার্টি লাইসেন্সসমূহ"},
{"This will create a compressed ZIP archive containing all your sites and databases.", "এটি আপনার সমস্ত সাইট এবং ডাটাবেস সম্বলিত একটি কম্প্রেসড ZIP আর্কাইভ তৈরি করবে।"},
{"Tips", "টিপস"},
{"TLD", "TLD"},
{"To use the local AI Assistant, you need to install and start Ollama.", "লোকাল এআই অ্যাসিস্ট্যান্ট ব্যবহার করতে, আপনাকে Ollama ইনস্টল এবং চালু করতে হবে।"},
{"Toggle bundled extensions per PHP version. Changes reload php-cgi automatically.", "প্রতিটি PHP ভার্সনের জন্য বান্ডেল করা এক্সটেনশন টগল করুন। পরিবর্তনের ফলে php-cgi স্বয়ংক্রিয়ভাবে রিলোড হবে।"},
{"token", "token"},
{"Uninstall", "আনইনস্টল করুন"},
{"Update DNS Record", "DNS রেকর্ড আপডেট করুন"},
{"upload_max_filesize", "upload_max_filesize"},
{"Uptime", "আপটাইম"},
{"Use as default", "ডিফল্ট হিসেবে ব্যবহার করুন"},
{"Use SSL/TLS", "SSL/TLS ব্যবহার করুন"},
{"user password (MySQL, optional)", "ব্যবহারকারীর পাসওয়ার্ড (MySQL, ঐচ্ছিক)"},
{"Username", "ইউজারনেম"},
{"username", "ইউজারনেম"},
{"Username / Email", "ইউজারনেম / ইমেল"},
{"version (e.g. 20, 22, lts)", "ভার্সন (যেমন 20, 22, lts)"},
{"Version (e.g. 8.4)", "ভার্সন (যেমন 8.4)"},
{"Version 1.0.0", "ভার্সন 1.0.0"},
{"Versions", "ভার্সনসমূহ"},
{"View intercepted emails sent by your local apps (via Mailpit) without opening a browser.", "ব্রাউজার না খুলেই আপনার লোকাল অ্যাপস থেকে পাঠানো ইন্টারসেপ্টেড ইমেলগুলি (Mailpit-এর মাধ্যমে) দেখুন।"},
{"View logs", "লগ দেখুন"},
{"VS Code Integration", "VS Code ইন্টিগ্রেশন"},
{"Vue", "Vue"},
{"Vue 3 + Vite", "Vue 3 + Vite"},
{"Waiting for authorization...", "অনুমোদনের জন্য অপেক্ষা করা হচ্ছে..."},
{"Watch files (like error.log or access.log) in real-time.", "রিয়েল-টাইমে ফাইলগুলি (যেমন error.log বা access.log) পর্যবেক্ষণ করুন।"},
{"Web Application Firewall (WAF)", "ওয়েব অ্যাপ্লিকেশন ফায়ারওয়াল (WAF)"},
{"Web Server", "ওয়েব সার্ভার"},
{"Web tools", "ওয়েব টুলস"},
{"Websites", "ওয়েবসাইটসমূহ"},
{"We're here to help! Choose the best way to get in touch or contribute to the project.", "আমরা সাহায্য করতে প্রস্তুত! যোগাযোগ করার বা প্রজেক্টে অবদান রাখার সেরা উপায়টি বেছে নিন।"},
{"Windows PowerShell", "Windows PowerShell"},
{"Windows Subsystem for Linux — default distro", "Windows Subsystem for Linux — ডিফল্ট ডিস্ট্রো"},
{"WordPress", "WordPress"},
{"WordPress (blog)", "WordPress (blog)"},
{"Working directory", "ওয়ার্কিং ডিরেক্টরি"},
{"WSL", "WSL"},
{"XXXX-YYYY", "XXXX-YYYY"},
{"Yii 2", "Yii 2"},
{"zend", "zend"},
{"Zend Ext", "Zend Ext"},
{"Zone ID", "Zone ID"},
{"🚀 Deploy Now", "🚀 এখনই ডিপ্লয় করুন"},
{"Compress to ZIP", "ZIP-এ কম্প্রেস করুন"},
{"Extract ZIP", "ZIP এক্সট্র্যাক্ট করুন"},
{"New File", "নতুন ফাইল"},
{"New Folder", "নতুন ফোল্ডার"},
{"Rename", "নাম পরিবর্তন করুন"},
{"Reveal in Explorer", "Explorer-এ দেখান"},
{"Save File", "ফাইল সেভ করুন"},
{"On — sites stay up in the background", "চালু — ব্যাকগ্রাউন্ডে সাইটগুলো চালু থাকবে"},
{"Off — closing the window quits BanglaHost", "বন্ধ — উইন্ডো বন্ধ করলে BanglaHost বন্ধ হয়ে যাবে"},
{"not installed", "ইনস্টল করা নেই"},
{"installed", "ইনস্টল করা আছে"},
{"running", "চলমান"},
{"stopped", "বন্ধ"},
{"working…", "কাজ চলছে…"},
{"done", "সম্পন্ন"},
{"failed", "ব্যর্থ"},
{"Web servers", "ওয়েব সার্ভারসমূহ"},
{"Mail", "মেইল"},
{"Languages / runtimes", "ল্যাঙ্গুয়েজ / রানটাইম"},
{"AI models", "AI মডেলসমূহ"},
{"Java", "Java"},
{"Version control", "ভার্সন কন্ট্রোল"},
{"Tools", "টুলস"},
        };
    }
}
