using System.Diagnostics;
using System.Text;

namespace BanglaHost.Core;

/// <summary>
/// Optional Apache backend (for sites that need native .htaccess). nginx stays the
/// front (TLS + :80/:443) and proxies the host to Apache on 127.0.0.1:8080, which
/// serves with AllowOverride All and hands .php to php-cgi via mod_proxy_fcgi.
/// Windows-specific vs the mac engine: the winnt MPM, module paths under the build's
/// <c>modules\</c>, no User/Group/unixd, and forward-slash paths.
/// </summary>
public static class Apache
{
    public const int Port = 8080;
    private static string Dir => Path.Combine(Paths.Home, "apache");
    private static string Conf => Path.Combine(Dir, "httpd.conf");
    private static string SitesDir => Path.Combine(Dir, "sites");
    private static string PidFile => Path.Combine(Paths.Run, "httpd.pid");

    public static bool Available => Tools.HttpdExe() is not null;

    public static bool Running()
    {
        return NetUtils.IsListening(Port, 500);
    }

    private static string Fwd(string p) => p.Replace('\\', '/');

    /// <summary>Shared php.ini for CGI mode. mod_cgi rejects any pre-header stdout, so
    /// PHP MUST NOT print startup warnings/errors ("Bad header: &lt;br /&gt;" 500s). We log them
    /// instead. cgi.force_redirect=0 is required when Apache invokes php-cgi via Action.</summary>

    public static void RenderMain()
    {
        var root = Tools.ApacheRoot() ?? throw new BhException("Apache not installed");
        var mods = Fwd(Path.Combine(root, "modules"));
        var home = Fwd(Paths.Home);
        Directory.CreateDirectory(SitesDir);
        var sb = new StringBuilder();
        sb.Append($$"""
        # Generated by BanglaHost (Windows) Ã¯Â¿Â½ Apache backend behind nginx. Do not edit by hand.
        ServerRoot "{{Fwd(root)}}"
        Listen 127.0.0.1:{{Port}}
        # (the winnt MPM is compiled into httpd.exe on Windows Ã¯Â¿Â½ no LoadModule needed)
        LoadModule authz_core_module {{mods}}/mod_authz_core.so
        LoadModule dir_module {{mods}}/mod_dir.so
        LoadModule mime_module {{mods}}/mod_mime.so
        LoadModule rewrite_module {{mods}}/mod_rewrite.so
        LoadModule headers_module {{mods}}/mod_headers.so
        LoadModule setenvif_module {{mods}}/mod_setenvif.so
        LoadModule log_config_module {{mods}}/mod_log_config.so
        LoadModule env_module {{mods}}/mod_env.so
        LoadModule alias_module {{mods}}/mod_alias.so
        LoadModule cgi_module {{mods}}/mod_cgi.so
        LoadModule actions_module {{mods}}/mod_actions.so
        ServerName localhost
        PidFile "{{home}}/run/httpd.pid"
        DefaultRuntimeDir "{{home}}/run"
        TypesConfig "{{Fwd(root)}}/conf/mime.types"
        DirectoryIndex index.php index.html index.htm
        ErrorLog "{{home}}/logs/apache-error.log"
        LogLevel warn
        LimitRequestBody 0
        <Directory />
            AllowOverride none
            Require all denied
        </Directory>
        IncludeOptional "{{home}}/apache/sites/*.conf"

        """);
        Directory.CreateDirectory(Path.GetDirectoryName(Conf)!);
        File.WriteAllText(Conf, sb.ToString());
    }

    /// <summary>Per-site Apache vhost: serves <paramref name="root"/> with .htaccess; .php runs
    /// via mod_cgi + Action (Apache spawns php-cgi.exe per request Ã¯Â¿Â½ the reliable Windows path;
    /// mod_proxy_fcgi over TCP corrupts SCRIPT_FILENAME with the C:\ drive letter).</summary>
    public static void RenderVhost(string name, string domain, string root, string phpKey, Config cfg)
    {
        // NEVER emit an empty DocumentRoot: a single bad vhost makes `httpd -t` fail and
        // Apache refuses to start at all, taking down EVERY Apache-backed site (502s across
        // the board). Fail fast with a clear message so the bad site gets fixed instead.
        if (string.IsNullOrWhiteSpace(root))
            throw new BhException($"Site '{name}': web root is empty — set it first (`banglahost site root {name} <path>`). Refusing to write an Apache vhost with an empty DocumentRoot.");
        root = root.Trim().Trim('"').Trim();
        var version = Services.PhpVersion(phpKey, cfg);
        var phpExe = Tools.PhpCgiExe(version);
        var phpDir = phpExe is not null ? Fwd(Path.GetDirectoryName(phpExe)!) : "";
        var home = Fwd(Paths.Home);
        var iniDir = Fwd(Path.Combine(Paths.Home, "apache"));
        Directory.CreateDirectory(SitesDir);
var body = $$"""
        # BanglaHost Apache backend: {{name}} ({{domain}}) php={{phpKey}}
        <VirtualHost 127.0.0.1:{{Port}}>
            ServerName {{domain}}
            DocumentRoot "{{Fwd(root)}}"
            <Directory "{{Fwd(root)}}">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>
            ScriptAlias "/__bhphp/" "{{phpDir}}/"
            <Directory "{{phpDir}}">
                Require all granted
                Options +ExecCGI
            </Directory>
            Action application/x-httpd-php "/__bhphp/php-cgi.exe"
            AddType application/x-httpd-php .php
            ErrorLog "{{home}}/logs/{{name}}-apache-error.log"
        </VirtualHost>

        """;
        File.WriteAllText(Path.Combine(SitesDir, $"{name}.conf"), body);
    }

    public static void RemoveVhost(string name)
    {
        try { File.Delete(Path.Combine(SitesDir, $"{name}.conf")); } catch { }
    }

    /// <summary>Validate the config (httpd -t -f conf). Returns (ok, output).
    /// Bounded wait, concurrent pipe reads (C2/C5).</summary>
    private static (bool ok, string output) Test()
    {
        var exe = Tools.HttpdExe()!;
        var res = ProcRunner.Run(exe, new[] { "-t", "-f", Fwd(Conf) },
            workingDir: Path.GetDirectoryName(exe), timeoutMs: 60_000);
        var outp = res.TimedOut ? $"timed out\n{res.All}" : res.All;
        return (!res.TimedOut && outp.Contains("Syntax OK"), outp);
    }

    public static (bool ok, string msg) Start()
    {
        var exe = Tools.HttpdExe();
        if (exe is null) return (false, "Apache not installed (no httpd.exe)");
        RenderMain();
        if (Running()) return (true, "apache already running");

        var cfg = Config.Load();
        if (!NetUtils.IsPortAvailable(Port)) throw new BhException($"Port {Port} is already in use by another application. Please stop it before starting Apache.");

        var (tok, tmsg) = Test();
        if (!tok) return (false, "apache config test failed:\n" + tmsg);

        // Run httpd directly (NOT -k start, which controls a Windows service). Detach
        // like nginx: redirect streams so it doesn't hold the caller's console.
        var psi = new ProcessStartInfo
        {
            FileName = exe,
            UseShellExecute = false, CreateNoWindow = true,
            RedirectStandardOutput = true, RedirectStandardError = true,
            WorkingDirectory = Path.GetDirectoryName(exe)!,
        };
        psi.ArgumentList.Add("-f");
        psi.ArgumentList.Add(Fwd(Conf));
        var p = Process.Start(psi)!;

        JobManager.Add(p);

        for (var i = 0; i < 12 && !Running(); i++) System.Threading.Thread.Sleep(300);
        return Running() ? (true, $"apache started (:{Port})") : (false, "apache failed to start (see logs\\apache-error.log)");
    }

    public static void Stop()
    {
        try
        {
            if (File.Exists(PidFile) && int.TryParse(File.ReadAllText(PidFile).Trim(), out var pid))
                BanglaHost.Core.ProcessUtils.KillSafeChecked(pid, "httpd", "httpd.exe");
        }
        catch { }
        try { File.Delete(PidFile); } catch { }
    }

    public static void Reload()
    {
        if (Tools.HttpdExe() is null || !Running()) return;
        Stop();
        System.Threading.Thread.Sleep(300);
        Start();
    }
}
